name: 'EAP component deploy action'
description: 'Continuous build and deployment of EAP components.'
inputs:
  token:
    description: 'The secret required for the deployment to the EAP nexus'
    required: true
  additional-params:
    description: 'By default, the action runs `mvn clean deploy` command. You can use this input if you want to add any additional parameters.'
    required: false
runs:
  using: "composite"
  steps:
    - run: |
        if [ -z "${{inputs.token}}" ]; then
          echo "The token was not supplied. Exiting."
          exit 1
        fi
        cd $GITHUB_ACTION_PATH
        gpg --quiet --batch --yes --decrypt --passphrase="${{inputs.token}}" --output maven-settings.xml ./maven-settings.xml.gpg
        cd $GITHUB_WORKSPACE
        NEW_VERSION=$(mvn -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec)-$(git rev-parse --short HEAD)-$(date -u '+%Y%m%d%H%M%S')
        echo "Setting version to $NEW_VERSION"
        mvn versions:set -DnewVersion=$NEW_VERSION
        mvn clean deploy -s $GITHUB_ACTION_PATH/maven-settings.xml -DaltDeploymentRepository=openshift-nexus::default::https://nexus-nexus.6923.rh-us-east-1.openshiftapps.com/repository/eap-components/ ${{inputs.additional-params}}
      shell: bash

